id: P004633
initial_creation_type: ocr
source_metadata:
  id: bdr:W24047
  title: རྒྱལ་ཡུམ་གསང་བ་ཡེ་ཤེས་ལས་འཕྲོས་པའི་ཐེག་པ་སྤྱི་དང་བྱེ་བྲག་གི་ཆོས་འབྱུང་འཁྲུལ་མུན་སེལ་བྱེད་ལུང་རིག་ཉི་མའི་འོད་ཟེར
  author: ''
  volumes:
    5edbd811e2d04143bae0c81b440d12f3:
      image_group_id: I3644
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
