id: opecha:P004633
initial_creation_type: ocr
source_metadata:
  id: bdr:W24047
  title: རྒྱལ་ཡུམ་གསང་བ་ཡེ་ཤེས་ལས་འཕྲོས་པའི་ཐེག་པ་སྤྱི་དང་བྱེ་བྲག་གི་ཆོས་འབྱུང་འཁྲུལ་མུན་སེལ་བྱེད་ལུང་རིག་ཉི་མའི་འོད་ཟེར
  volume: ''
  author: ''
