id: IB77F7661
legacy_id: P004633
ocr_import_info:
  bdrc_scan_id: W24047
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T12:48:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:23:42.455743+00:00'
last_modified: 2022-09-02 13:23:59.380004
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24047
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24047
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་ཡུམ་གསང་བ་ཡེ་ཤེས་ལས་འཕྲོས་པའི་ཐེག་པ་སྤྱི་དང་བྱེ་བྲག་གི་ཆོས་འབྱུང་འཁྲུལ་མུན་སེལ་བྱེད་ལུང་རིག་ཉི་མའི་འོད་ཟེར།
  author: འཇིགས་མེད་འཕྲིན་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.7171000010500818
  ocr_word_median_confidence_index: 0.8050000071525574
quality: null
bases:
  I3644:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3644
      total_pages: 190
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3644.txt
    statistics:
      ocr_word_median_confidence_index: 0.8050000071525574
      ocr_word_mean_confidence_index: 0.7171000010500818
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
